### PR TITLE
Remove crate const-generic flag

### LINKED ISSUE #27: Support for `min_const_generics`?
I tried using this crate with 
```
#![feature(min_const_generics)]

use array_init;

struct Bar(u32);

impl Default for Bar {
    fn default() -> Bar {
        Bar(13)
    }
}

struct Foo<const N: usize> {
    foo: [Bar; N]
}

impl<const N: usize> Foo<N> {
    fn new() -> Self {
        Self {
            foo: array_init::array_init(|_| Default::default())
        }
    }
}
```

but it fails with

```
error[E0277]: the trait bound `[Bar; N]: IsArray` is not satisfied
   --> crates/storage/src/lazy/lazy_array.rs:267:13
    |
12 |             array_init::array_init(|_| Default::default());
    |             ^^^^^^^^^^^^^^^^^^^^^^ the trait `IsArray` is not implemented for `[Bar; N]`
    | 
   ::: ~/.cargo/registry/src/github.com-1ecc6299db9ec823/array-init-1.0.0/src/lib.rs:89:12
    |
89  |     Array: IsArray,
    |            ------- required by this bound in `array_init`
    |
    = help: the following implementations were found:
              <[T; 0] as IsArray>
              <[T; 100] as IsArray>
              <[T; 101] as IsArray>
              <[T; 102] as IsArray>
            and 509 others
```

Is support for `min_const_generics` something you want to implement?

### PR DESCRIPTION
**Pull request by NULLx76**
This PR removes the crate flag for const generic as this is now available in stable. The code for the non-const-generic version has just been removed as it seems redundant now.

I've also bumped the version as discussed in #28, I wasn't sure how the need to update your compiler falls within semver scheme but I've simply chosen for a minor increment, if you think it should be a major or patch instead you or I can of course change this. 

Closes #27

### CODE REVIEW

**Comment by Manishearth** [comment]
Published, thanks!

**Comment by aeikum** [comment]
We are using Rust 1.50 still and this broke our build :( I'm not sure what the "right" thing to do here is -- ask your project to continue to support some older compilers, or pin our use of your library to an older version, or... something else?

**Comment by Manishearth** [comment]
Please pin; this crate does not have an MSRV policy

**Comment by Manishearth** [comment]
I could yank given that I'm about to make a 2.0 release anyway

**Comment by NULLx76** [comment]
I was kind of afraid that this might happen hence my comment about semver, but as the public api didn't change I just opted for minor.

**Comment by Manishearth** [comment]
1.1.0 has been yanked.

**Pull request merged**
